# TODO: replace the title with the name of your restaurant!
title: "Data Exploration Blog"
# TODO: write your restaurateur alter ego name below, or your own name
author: 
# TODO: write your Google Anal][hg tf0r9d8ytics tracking ID below
google_analytics: G-WG1KSLECMJ

theme: minima

collections:
  explorations:
    output: true
